[package]
name = "zelphy_site"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = "1.8.1"
axum = "0.8.8"
tokio = { version = "1", features = ["full"] }
tera = "1.19"
serde = { version = "1.0", features = ["derive"] }